### ISSUE TITLE
Product Page Main Image not appear with RTL Mode

### ISSUE THREAD

**Issue by ahmedadelnew** [woocommerce/storefront#903]
I'm using Woocommerce last version and also download storefront theme last version 2.3.2
I'm using the **Arabic language** on my site, and product image in product page not showing till clicking on zoom icon it appears, and when changing site language to English from (Setting > General) everything working fine and product image in product page appear.
This problem found when adding **additional images** to a product, and when adding the main image only everything working fine, and when adding additional images to **product gallery images** the images not shown expect to click on zoom icon.
I'm not adding any custom functions and not editing anything.
The RTL file in theme code and named "style-rtl.css" and don't changing anything on it.
The RTL mode working fine in all site expect the product page main image
I'm not editing on any image size or image width on any plugin or theme customizer
I tested storefront theme on another site (for testing) and enabled the woocommerce plugin and also the same issue **when changing the language to Arabic**.
This photo explains the problem (if gif image not showing go to this URL https://goo.gl/bytJqq)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39780418/40751669-75f7148c-646c-11e8-9f43-13e4f9e9d7b4.gif)

**#I found someone has the same problem and he said it was from Woocommerce the last update
his problem link**
https://github.com/woocommerce/woocommerce/issues/20311

**Comment by ahmedadelnew** [comment]
**I found someone has the same problem and he said it was from Woocommerce the last update
his problem link**
https://github.com/woocommerce/woocommerce/issues/20311
![40738458-e92c635e-6443-11e8-89a1-e7ab3788f5a5](https://user-images.githubusercontent.com/39780418/40752651-bf677324-6470-11e8-801a-fd36bbc47685.jpg)

**Comment by tiagonoronha** [comment]
@ahmedadelnew this is WooCommerce issue that has been fixed in 3.4.2. Please update WooCommerce to the latest version.

Related pull request: https://github.com/woocommerce/woocommerce/pull/20321

**Comment by mkhattawi** [comment]
Hi, I do face the same exact issue but in **WooCommerce 3.6.5**, I also have **Arabic** (RTL) storefront and the same issue persists.
One image products show just normal while **multi-image** products wouldn't display the images unless clicking on zoom.

See the issue in below link:
https://store.techgigz.com/product/centrophorus-redragon/

Please Help!

**Comment by patzu** [comment]
> Hi, I do face the same exact issue but in **WooCommerce 3.6.5**, I also have **Arabic** (RTL) storefront and the same issue persists.
> One image products show just normal while **multi-image** products wouldn't display the images unless clicking on zoom.
> 
> See the issue in below link:
> https://store.techgigz.com/product/centrophorus-redragon/
> 
> Please Help!

I have the same problem in Wordpress 5.5.1, How to solve this issue?
